# Generated by Django 2.2.3 on 2019-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
